---
- name: Install Nginx and configure site
  hosts: web_servers
  become: yes

  vars:
    domain_name: test.com
    ssl_enabled: true
    ssl_certificate_path: /path/to/ssl/certificate.pem
    ssl_key_path: /path/to/ssl/private-key.pem
    php_socket: /php-fpm.sock
    php_fpm_log_path: /php-fpm.log
    php_fpm_worker_count: 4

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Create directory for the website
      file:
        path: /{{ domain_name }}
        state: directory
        owner: www-data
        group: www-data
        mode: 0755

    - name: Nginx config
      template:
        src: nginx_config.j2
        dest: /etc/nginx/sites-available/{{ domain_name }}


    - name: Create PHP-FPM config file from template
      template:
        src: php_fpm_config.j2
        dest: /etc/php/{{ php_version }}/fpm/php-fpm.conf


